version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "LambdaDynamoDBApp"  # Your Lambda function name
        Alias: "prod"              # Replace with the alias you created
        CurrentVersion: 1          # Replace with the current published version number
