version: 0.0
Resources:
  - LambdaDeploymentResource:
      Type: AWS::Lambda::Function
      Properties:
        Name: "LambdaDynamoDBApp"   # Replace with your actual Lambda function name
        Alias: "prod"               # Replace with your alias